version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - WEB_PORT=3000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./reportes:/app/reportes
      - bot_db:/app/db_data
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  bot_db:
    driver: local

networks:
  bot-network:
    driver: bridge